/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_09 (number 3), LPUART1_RXD/J56[2] */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                      RXD   /*!< LPUART1 signal: RXD */

/* GPIO_10 (number 2), LPUART1_TXD/J56[4] */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                      TXD   /*!< LPUART1 signal: TXD */

/* GPIO_AD_05 (number 55), LPSPI1_PCS0/INT1_COMBO/J56[6]/J57[6]/U26[11]/U27[1] */
#define BOARD_INITPINS_LPSPI1_PCS0_PERIPHERAL                             LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_LPSPI1_PCS0_SIGNAL                                   PCS0   /*!< LPSPI1 signal: PCS0 */

/* GPIO_AD_06 (number 52), LPSPI1_SCK/INT2_COMBO/J56[8]/J57[12]/U26[9]/U27[6] */
#define BOARD_INITPINS_LPSPI1_SCK_PERIPHERAL                              LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_LPSPI1_SCK_SIGNAL                                     SCK   /*!< LPSPI1 signal: SCK */

/* GPIO_AD_03 (number 57), LPSPI1_SDI/J57[10]/U27[2] */
#define BOARD_INITPINS_LPSPI1_SDI_PERIPHERAL                              LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_LPSPI1_SDI_SIGNAL                                     SDI   /*!< LPSPI1 signal: SDI */

/* GPIO_AD_04 (number 56), LPSPI1_SDO/J57[8]/U27[5] */
#define BOARD_INITPINS_LPSPI1_SDO_PERIPHERAL                              LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_LPSPI1_SDO_SIGNAL                                     SDO   /*!< LPSPI1 signal: SDO */

/* GPIO_08 (number 4), SAI1_MCLK/U10[11] */
#define BOARD_INITPINS_SAI1_MCLK_PERIPHERAL                                GPIO1   /*!< Device name: GPIO1 */
#define BOARD_INITPINS_SAI1_MCLK_SIGNAL                               gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_INITPINS_SAI1_MCLK_CHANNEL                                      8U   /*!< GPIO1 gpiomux_io channel: 08 */

/* GPIO_01 (number 12), I2C1_SDA/U10[18]/J57[18]/U26[6] */
#define BOARD_INITPINS_I2C1_SDA_PERIPHERAL                                 GPIO1   /*!< Device name: GPIO1 */
#define BOARD_INITPINS_I2C1_SDA_SIGNAL                                gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_INITPINS_I2C1_SDA_CHANNEL                                       1U   /*!< GPIO1 gpiomux_io channel: 01 */

/* GPIO_AD_01 (number 59), ADC12_1/J26[10]/J56[14] */
#define BOARD_INITPINS_ADC12_1_PERIPHERAL                                  GPIO1   /*!< Device name: GPIO1 */
#define BOARD_INITPINS_ADC12_1_SIGNAL                                 gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_INITPINS_ADC12_1_CHANNEL                                       15U   /*!< GPIO1 gpiomux_io channel: 15 */

/* GPIO_AD_02 (number 58), ADC12_2/J26[12]/J56[16] */
#define BOARD_INITPINS_ADC12_2_PERIPHERAL                                  GPIO1   /*!< Device name: GPIO1 */
#define BOARD_INITPINS_ADC12_2_SIGNAL                                 gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_INITPINS_ADC12_2_CHANNEL                                       16U   /*!< GPIO1 gpiomux_io channel: 16 */

/* GPIO_SD_02 (number 74), GPIO_SD_02/BT_CFG[0]/J57[2]/TP34 */
#define BOARD_INITPINS_GPIO_SD_02_GPIO                                     GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_GPIO_SD_02_PORT                                     GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_GPIO_SD_02_PIN                                         2U   /*!< GPIO2 pin index: 2 */

/* GPIO_03 (number 10), SAI1_RXD0/U10[16] */
#define BOARD_INITPINS_SAI1_RXD0_PERIPHERAL                                GPIO1   /*!< Device name: GPIO1 */
#define BOARD_INITPINS_SAI1_RXD0_SIGNAL                               gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_INITPINS_SAI1_RXD0_CHANNEL                                      3U   /*!< GPIO1 gpiomux_io channel: 03 */

/* GPIO_AD_07 (number 51), ADC12_3/J26[2] */
#define BOARD_INITPINS_ADC12_3_PERIPHERAL                                  GPIO1   /*!< Device name: GPIO1 */
#define BOARD_INITPINS_ADC12_3_SIGNAL                                 gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_INITPINS_ADC12_3_CHANNEL                                       21U   /*!< GPIO1 gpiomux_io channel: 21 */

/* GPIO_AD_09 (number 48), ADC12_4/JTAG_TDO/J55[6]/J26[4] */
#define BOARD_INITPINS_ADC12_4_PERIPHERAL                                  GPIO1   /*!< Device name: GPIO1 */
#define BOARD_INITPINS_ADC12_4_SIGNAL                                 gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_INITPINS_ADC12_4_CHANNEL                                       23U   /*!< GPIO1 gpiomux_io channel: 23 */

/* GPIO_AD_10 (number 47), ADC12_5/JTAG_TDI/J55[8]/J26[6] */
#define BOARD_INITPINS_ADC12_5_PERIPHERAL                                  GPIO1   /*!< Device name: GPIO1 */
#define BOARD_INITPINS_ADC12_5_SIGNAL                                 gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_INITPINS_ADC12_5_CHANNEL                                       24U   /*!< GPIO1 gpiomux_io channel: 24 */

/* GPIO_AD_14 (number 43), ADC12_6/J26[8] */
#define BOARD_INITPINS_ADC12_6_PERIPHERAL                                  GPIO1   /*!< Device name: GPIO1 */
#define BOARD_INITPINS_ADC12_6_SIGNAL                                 gpiomux_io   /*!< GPIO1 signal: gpiomux_io */
#define BOARD_INITPINS_ADC12_6_CHANNEL                                       28U   /*!< GPIO1 gpiomux_io channel: 28 */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
